apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wired-tag-query.fullname" . }}
  labels:
    {{- include "wired-tag-query.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wired-tag-query.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wired-tag-query.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wired-tag-query.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GREENPLUM_DB_HOST
              value: "18.142.49.13"
            - name: GREENPLUM_DB_PORT
              value: "5432"
            - name: GREENPLUM_DB_NAME
              value: "eth"
            - name: GREENPLUM_DB_USERNAME
              value: "gpadmin"
            - name: GREENPLUM_DB_PASSWORD
              value: "PbIzajLzDfQ62"
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: DB_USERNAME
              value: {{ .Values.database.username | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: READ_ONLY_DB_HOST
              value: {{ .Values.readonlyDatabase.host | quote }}
            - name: READ_ONLY_DB_NAME
              value: {{ .Values.readonlyDatabase.name | quote }}
            - name: READ_ONLY_DB_USERNAME
              value: {{ .Values.readonlyDatabase.username | quote }}
            - name: READ_ONLY_DB_PASSWORD
              value: {{ .Values.readonlyDatabase.password | quote }}
            - name: RD_HOST
              value: {{ .Values.redis.host }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
