networks:
  relation-network:
    driver: bridge

services:
  relation-redis:
    container_name: relation-redis
    image: redis:latest
    networks:
      relation-network: {}
    hostname: relation-redis
    ports:
      - 127.0.0.1:6379:6379/tcp

  relation-postgres:
    container_name: relation-postgres
    environment:
      POSTGRES_PASSWORD: hojil@123!
    image: postgres:14
    networks:
      relation-network: {}
    hostname: relation-postgres
    ports:
      - 5432:5432
    volumes:
      - /opt/data/postgres/data:/var/lib/postgresql/data

  # once
  relation-tag-query:
    container_name:   relation-tag-query
    environment:
      DB_HOST: relation-postgres
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: hojil@123!
      RDS_HOST: relation-redis
      GREENPLUM_DB_HOST : ec2-18-142-49-13.ap-southeast-1.compute.amazonaws.com
      GREENPLUM_DB_PORT : 5432
      GREENPLUM_DB_NAME : eth
      GREENPLUM_DB_USERNAME : gpadmin
      GREENPLUM_DB_PASSWORD :  hojil@123!
      READ_ONLY_DB_HOST : 127.0.0.1
      READ_ONLY_DB_PORT : 5432
      READ_ONLY_DB_NAME : eth
      READ_ONLY_DB_USERNAME : postgres
      READ_ONLY_DB_PASSWORD :  hojil@123!
      JOB_IDENTIFIER: relation-tag-query
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      relation-network: {}
    ports:
      - 10009:10009
    depends_on:
      - relation-postgres
      - relation-redis