server:
  port: ${PORT:10009}
  base-url: /ugc

spring:
  application:
    name: relation-tag-query
  swagger:
    enabled: true
  datasource:
    primary:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?currentSchema=public&characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&stringtype=unspecified
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:hojil@123!}
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver
      #      druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      filters: stat,config

opensearch:
  rest:
    host: ${OPENSEARCH_HOST:localhost}
    port: ${OPENSEARCH_PORT:443}
# 日志配置
logging:
  config: classpath:logback-spring-yun.xml
